name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  connect-to-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug key contents (masked)
        run: echo "${{ secrets.VM_SSH_KEY }}" | head -n 2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "hello world!"
    #        cd /path/to/app
    #        git pull
    #        ./restart-app.sh
